### ISSUE TITLE
Add Readme file to your project

### ISSUE THREAD

**Issue by oladhari** [morinagahikaru/Myintro2#1]
please add a readme file to your project with details of :

- [x] used technologies
- [x] purpose of the project
- [x] link to the hosted web page of this folder

[here](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) a template of Readme file

**Comment by Hikarun15** [comment]
I added a readme file to my project!

**Comment by oladhari** [comment]
the link to the website page shows the GitHub folder and not the rendered page

**Comment by Hikarun15** [comment]
Sorry, I fixed it!

**Comment by oladhari** [comment]
after finishing the issue, please close it
